server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/angeelsanchez/employees-microservices
          search-paths: gateway
  application:
    name: config-service